#!/bin/bash


# proudly generated by ChatGPT XD 

while true; do
  # Find processes with reverse shell characteristics (adjust the patterns as needed)
  reverse_shell_pid=$(ps -e -o pid,args | grep -E "(python[0-9.]*\s+-c\s+|bash\s+-i\s+|socat\s+TCP-LISTEN|nc\s+-[[:alnum:]]*e\s+/bin/(bash|sh)|perl\s+-M|php\s+-r|ruby\s+-rsocket\s+-e|java\s+ProcessBuilder|lua\s+-e|openssl\s+s_client|telnet\s+\d+|\bwar\b|\bnc\s+-l\s+\d+|go\s+run\s+|dart\s+run\s+|awk\s+'{print\s\$\0}'|c\s+&(.)\s+c)" | grep -v grep | awk '{print $1}')

  # If a reverse shell process is found, terminate it and print the closed command
  if [ -n "$reverse_shell_pid" ]; then
    closed_command=$(ps -p "$reverse_shell_pid" -o args=)
    echo "Reverse shell process with PID: $reverse_shell_pid and command: $closed_command closed. Terminating..."
    kill -9 "$reverse_shell_pid"
  fi

  # Wait for 5 seconds before checking again
  sleep 5
done
